import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body>
				<div>
					<header className="h-19 border">
						<h1 className="text-center">HEADER</h1>
					</header>
					{children}
				</div>
			</body>
		</html>
	)
}
